### ISSUE TITLE
Sync with multiple account fail

### ISSUE THREAD

**Issue by marcosinigaglia** [sybrex/django-instagram-profile#7]
Hi, I connect two account but I think there is an issue [here](https://github.com/sybrex/django-instagram-profile/blob/d22fc97b428cf224eddd93e31d77d991503a0671/instagram_profile/services.py#L32).
If you get the latest post date without filtering by the current profile you don't get correctly latest post in both account.
Thanks.

**Comment by sixthgear** [comment]
I found the same issue and submitted a PR to correct it.
